### ISSUE TITLE
Make this page Responsive

### ISSUE THREAD

**Issue by Shoyebaktar-shirol** [Shoyebaktar-shirol/Personal-Portfolio#1]
Issue Description:
"Enhance the current page layout to be more responsive for better user experience on various devices."

**NOTE: Please read the [Contribution Guidelines] in the README.md file before contributing.**

**Comment by Tashuuuu** [comment]
Can I make it more responsive using Bootstrap?

**Comment by Shoyebaktar-shirol** [comment]
@Tashuuuu , yes u can make sure to follow me and feel free to ask anything related issues.

**Comment by Shoyebaktar-shirol** [comment]
hey @Tashuuuu any update ?

**Comment by Tashuuuu** [comment]
Currently working. Will share PR by EOD
